## Logistic Regression 

Binary Classification

In [149]:
from sklearn.datasets import load_iris

In [150]:
data = load_iris()

In [151]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [152]:
import pandas as pd

In [153]:
import seaborn as sns

In [154]:
df=sns.load_dataset('iris')

In [155]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [156]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [157]:
df['target_species']=data.target

In [158]:
df

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     target_species  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 6 columns]

In [159]:
# Taking only first two classes for binary classification
df1 = df[df['target_species']!=2]

In [160]:
df1

sepal_length  sepal_width  petal_length  petal_width     species  \
0            5.1          3.5           1.4          0.2      setosa   
1            4.9          3.0           1.4          0.2      setosa   
2            4.7          3.2           1.3          0.2      setosa   
3            4.6          3.1           1.5          0.2      setosa   
4            5.0          3.6           1.4          0.2      setosa   
..           ...          ...           ...          ...         ...   
95           5.7          3.0           4.2          1.2  versicolor   
96           5.7          2.9           4.2          1.3  versicolor   
97           6.2          2.9           4.3          1.3  versicolor   
98           5.1          2.5           3.0          1.1  versicolor   
99           5.7          2.8           4.1          1.3  versicolor   

    target_species  
0                0  
1                0  
2                0  
3                0  
4                0  
..             ...  
95               1  
96               1  
97               1  
98               1  
99               1  

[100 rows x 6 columns]

In [161]:
df1['target_species'].unique()

array([0, 1])

In [162]:
df1.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'target_species'],
      dtype='object')

In [163]:
from sklearn.model_selection import train_test_split

In [164]:
x= df1[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y=df1['target_species']

In [165]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [166]:
from sklearn.linear_model import LogisticRegression

In [167]:
classification = LogisticRegression(max_iter=200)

In [168]:
classification

LogisticRegression(max_iter=200)

In [169]:
classification.fit(x_train, y_train)

LogisticRegression(max_iter=200)

In [170]:
y_pred = classification.predict(x_test)

In [171]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1])

In [172]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [173]:
confusion_matrix(y_test, y_pred)

array([[17,  0],
       [ 0, 13]])

In [174]:
accuracy_score(y_test, y_pred)

1.0

In [175]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        13

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [176]:
from sklearn.model_selection import KFold

In [177]:
cv = KFold(n_splits=5)

In [178]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [179]:
from sklearn.model_selection import cross_val_score

In [180]:
scores=cross_val_score(classification, x_train, y_train, scoring='accuracy', cv=cv)

In [181]:
scores

array([1., 1., 1., 1., 1.])

In [182]:
import numpy as np
avg_score = np.mean(scores)

In [183]:
avg_score

1.0

In [184]:
# Takng a more comples dataset

from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [185]:
x,y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [186]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [187]:
complex_classification=LogisticRegression()

In [188]:
complex_classification

LogisticRegression()

In [189]:
complex_classification.fit(x_train, y_train)

LogisticRegression()

In [190]:
y_pred=complex_classification.predict(x_test)

In [191]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [192]:
confusion_matrix(y_test, y_pred)

array([[78, 13],
       [29, 80]])

In [193]:
accuracy_score(y_test, y_pred)

0.79

In [194]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [195]:
scores=cross_val_score(complex_classification, x_train, y_train, scoring='accuracy', cv=cv)

In [196]:
scores

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

In [197]:
# GridSearchCV 
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [198]:
parameters={'penalty':('l1','l2','elasticnet'), 'C':[1,10,20,30]}

In [199]:
classifier=LogisticRegression()

In [200]:
# Cross-validation with hyper-parameter tuning
clf = GridSearchCV(classifier, param_grid=parameters, cv=10)

In [201]:
clf.fit(x_train, y_train)

GridSearchCV(cv=10, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [202]:
# Best parameters
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [203]:
# To check the accuracy internally that is with CV
clf.best_score_

0.8099999999999999

In [204]:
# Now we would prepare our model using the above parameters
classifier=LogisticRegression(C=1, penalty='l2')

In [205]:
classifier.fit(x_train, y_train)

LogisticRegression(C=1)

In [206]:
y_pred=classifier.predict(x_test)

In [207]:
classifier.predict_proba(x_test)

array([[0.71649202, 0.28350798],
       [0.19508969, 0.80491031],
       [0.12418141, 0.87581859],
       [0.05045906, 0.94954094],
       [0.88775659, 0.11224341],
       [0.75067497, 0.24932503],
       [0.97980488, 0.02019512],
       [0.3921745 , 0.6078255 ],
       [0.59920135, 0.40079865],
       [0.39295203, 0.60704797],
       [0.20428696, 0.79571304],
       [0.80257879, 0.19742121],
       [0.86422932, 0.13577068],
       [0.92665682, 0.07334318],
       [0.00131743, 0.99868257],
       [0.04171096, 0.95828904],
       [0.56288536, 0.43711464],
       [0.89322764, 0.10677236],
       [0.29278211, 0.70721789],
       [0.00870994, 0.99129006],
       [0.71879454, 0.28120546],
       [0.5108267 , 0.4891733 ],
       [0.76230298, 0.23769702],
       [0.73170811, 0.26829189],
       [0.10155737, 0.89844263],
       [0.04046512, 0.95953488],
       [0.57926768, 0.42073232],
       [0.00526468, 0.99473532],
       [0.03101648, 0.96898352],
       [0.96093035, 0.03906965],
       [0.

So the category with the greater probability has been chosen in y_pred

In [208]:
confusion_matrix(y_test, y_pred)

array([[78, 13],
       [29, 80]])

In [209]:
# With more parameters
parameters={'penalty':('l1','l2','elasticnet'), 'C':[1,10,20,30], 
            'solver':('lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga')}

In [210]:
clf = GridSearchCV(classifier, param_grid=parameters, cv=5)

In [211]:
clf.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(C=1),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet'),
                         'solver': ('lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga')})

In [212]:
clf.best_params_

{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}

In [213]:
clf.best_score_

0.8087500000000001

In [214]:
# Randomized-search CV

In [215]:
from sklearn.model_selection import RandomizedSearchCV

In [216]:
# Cross-validation with hyper-parameter tuning
clf1=RandomizedSearchCV(LogisticRegression(), param_distributions=parameters, cv=5,n_iter=20)

In [217]:
clf1.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet'),
                                        'solver': ('lbfgs', 'liblinear',
                                                   'newton-cg',
                                                   'newton-cholesky', 'sag',
                                                   'saga')})

In [218]:
clf1.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 20}

In [219]:
# To check the accuracy internally that is with CV
clf.best_score_

0.8087500000000001

In [220]:
# Now we create our model with the above parameters
classifier=LogisticRegression(solver='newton-cg', penalty= 'l2', C= 20)

In [221]:
classifier.fit(x_train, y_train)

LogisticRegression(C=20, solver='newton-cg')

In [222]:
y_pred=classifier.predict(x_test)

In [223]:
confusion_matrix(y_test, y_pred)

array([[79, 12],
       [29, 80]])

In [224]:
accuracy_score(y_test, y_pred)

0.795

Multi-Class Classification

In [225]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression

In [226]:
x,y = make_classification(n_samples=1000, n_features=10, n_redundant=5, n_informative=5, n_classes=3, random_state=1)

In [227]:
x

array([[ 1.89149379, -0.39847585,  1.63856893, ...,  0.58810926,
        -0.02542177, -0.52835426],
       [ 1.86913773, -0.56336215,  2.03411807, ..., -0.55633   ,
        -0.27340013,  0.72129251],
       [ 1.95259701, -2.83144572,  0.19055535, ..., -0.60957741,
        -2.07750191, -1.75469982],
       ...,
       [ 1.98033054,  1.37228804,  1.67376262, ...,  2.75687956,
        -0.20719842,  0.39299534],
       [-1.54305631, -0.27530218,  0.38744703, ...,  0.72769107,
         0.51983329, -1.92306657],
       [ 1.17970389, -3.3812155 , -0.1498426 , ...,  1.24640268,
        -4.00356845, -3.01027048]])

In [228]:
y

array([1, 0, 1, 2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 2, 0, 1, 1, 0, 1, 0, 2, 0,
       2, 2, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 1, 2, 2, 2, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 1, 2, 1,
       1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 1, 2, 2, 2,
       0, 1, 0, 2, 1, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 2, 2,
       1, 2, 0, 2, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 0, 1,
       0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 2, 0, 1, 2, 0, 2, 1, 2, 0, 0, 1,
       0, 0, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0,
       2, 0, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 1, 1, 0,
       1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 2, 1, 1, 2, 0, 0, 0, 2, 2, 2, 0, 2,
       0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 0, 2, 2,
       1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2,
       1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1,
       1, 2, 1, 2, 2, 2, 1, 0, 0, 1, 0, 0, 2, 1, 1,

In [229]:
from sklearn.model_selection import train_test_split

In [230]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=40)

In [231]:
# We take 'solver' as 'lbfgs' as it can handel multinomial loss
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [232]:
from sklearn.model_selection import GridSearchCV

In [233]:
parameters={'penalty':('l1','l2','elasticnet'), 'C':[1,10,20,30], 'multi_class':('ovr', 'ovo')}

In [234]:
# Cross-validation with hyper-parameter tuning
gridcv = GridSearchCV(model, param_grid=parameters, cv=5)

In [235]:
gridcv.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(multi_class='ovr'),
             param_grid={'C': [1, 10, 20, 30], 'multi_class': ('ovr', 'ovo'),
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [236]:
gridcv.best_params_

{'C': 1, 'multi_class': 'ovr', 'penalty': 'l2'}

In [237]:
gridcv.best_score_

0.6814285714285715

In [238]:
# Now we create our multi-class model with the above parameters
multi_class_model=LogisticRegression(solver='lbfgs', penalty= 'l2', C= 1, multi_class='ovr')

In [239]:
multi_class_model.fit(x_train, y_train)

LogisticRegression(C=1, multi_class='ovr')

In [240]:
model.fit(x_train, y_train)

LogisticRegression(multi_class='ovr')

In [241]:
y_pred = model.predict(x_test)

In [242]:
model.predict_proba(x_test)

array([[0.51630009, 0.30431738, 0.17938253],
       [0.17815645, 0.26972042, 0.55212312],
       [0.5877709 , 0.09799388, 0.31423521],
       [0.63767135, 0.05479818, 0.30753047],
       [0.56731034, 0.08940865, 0.34328101],
       [0.56265676, 0.21791044, 0.2194328 ],
       [0.13522308, 0.81689931, 0.04787761],
       [0.47147455, 0.03393473, 0.49459073],
       [0.46627793, 0.24408277, 0.28963929],
       [0.04298772, 0.69878844, 0.25822384],
       [0.29127232, 0.67508915, 0.03363852],
       [0.29839259, 0.56874915, 0.13285826],
       [0.5063464 , 0.45587428, 0.03777931],
       [0.1994456 , 0.74784077, 0.05271363],
       [0.74287207, 0.07867384, 0.1784541 ],
       [0.57773127, 0.09694015, 0.32532857],
       [0.25408345, 0.57046253, 0.17545402],
       [0.08041476, 0.33381303, 0.5857722 ],
       [0.59737176, 0.09867596, 0.30395228],
       [0.51193322, 0.07989512, 0.40817166],
       [0.34809176, 0.06924248, 0.58266576],
       [0.39729695, 0.20619112, 0.39651193],
       [0.

In [243]:
confusion_matrix(y_test, y_pred)

array([[82, 24,  4],
       [14, 67, 20],
       [27, 11, 51]])

In [244]:
accuracy_score(y_test, y_pred)

0.6666666666666666